language: python

python:
  - 3.6

install:
  - pip install codecov
#  - pip install tf-nightly-2.0-preview --quiet
  - pip install tensorflow==2.1.0 --quiet

script:
  - python tests/general_checks_test.py
  - python tests/test_operations.py
  - coverage run tests/general_checks_test.py

after_success:
  - codecov