language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install --progress-bar off -r requirements.txt

script:
  - python tests/device_checks_test.py
  - coverage run tests/device_checks_test.py

after_success:
  - codecov